import type { Question } from "./types";

// 15問の定義
export const QUESTIONS: Question[] = [
  {
    id: "name_birth",
    text: "あなたのお名前と、生まれた年を教えてください",
    placeholder: "例：田中さくら",
    type: "text_with_year",
    emoji: "🍼",
    timelineLabel: "誕生",
    yearPlaceholder: "例：2000",
  },
  {
    id: "chapters",
    text: "あなたの人生に「章タイトル」をつけるとしたら？\n（例：第1章 ぐうたら期、第2章 本気出す期）",
    placeholder: "例：第1章 ぐるぐる迷子期",
    type: "chapters",
    emoji: "📖",
    timelineLabel: "人生の章",
    yearPlaceholder: "その章が始まった年",
  },
  {
    id: "longest",
    text: "今も続けていることで、一番長く続いていることは何ですか？いつ始めましたか？",
    placeholder: "例：日記を書くこと",
    type: "text_with_year",
    emoji: "🔥",
    timelineLabel: "ずっと続けていること",
    yearPlaceholder: "始めた年",
  },
  {
    id: "turning_point",
    text: "「あの選択をしたから今の私がある」という分岐点は？それはいつのこと？",
    placeholder: "例：地元を離れて上京した",
    type: "text_with_year",
    emoji: "🚀",
    timelineLabel: "運命の分岐点",
    yearPlaceholder: "その年",
  },
  {
    id: "dark_period",
    text: "人生で一番どん底だった時期はいつ？何があったの？",
    placeholder: "例：就活で全落ちして自信を失った",
    type: "text_with_year",
    emoji: "🌧️",
    timelineLabel: "試練の章",
    yearPlaceholder: "その年頃",
  },
  {
    id: "recovery",
    text: "そのどん底から、どうやって抜け出した？",
    placeholder: "例：友人に話を聞いてもらって、少しずつ立ち直った",
    type: "text",
    emoji: "☀️",
    timelineLabel: "再起の章",
  },
  {
    id: "golden",
    text: "「あの頃に戻りたいな」と思う時期はいつ？なぜ？",
    placeholder: "例：高校の部活が楽しすぎた",
    type: "text_with_year",
    emoji: "🌟",
    timelineLabel: "黄金期",
    yearPlaceholder: "その年頃",
  },
  {
    id: "black_history",
    text: "反対に、「二度と戻りたくない」時期はある？それはいつ？",
    placeholder: "例：中二病全開の中学時代…",
    type: "text_with_year",
    emoji: "🙈",
    timelineLabel: "黒歴史期",
    yearPlaceholder: "その年頃",
  },
  {
    id: "biggest_change",
    text: "自分が一番変わったと感じた出来事は？いつのこと？",
    placeholder: "例：海外一人旅で価値観が変わった",
    type: "text_with_year",
    emoji: "✨",
    timelineLabel: "転換点",
    yearPlaceholder: "その年",
  },
  {
    id: "let_go",
    text: "手放したことで、かえって良かったものは？（物・関係・習慣など）",
    placeholder: "例：SNSを消したら心が軽くなった",
    type: "text",
    emoji: "🕊️",
    timelineLabel: "手放したもの",
  },
  {
    id: "key_person",
    text: "今の自分に一番影響を与えた人との出会いは、いつ？",
    placeholder: "例：大学のゼミの先生、2020年",
    type: "text_with_year",
    emoji: "💕",
    timelineLabel: "大切な出会い",
    yearPlaceholder: "出会った年",
  },
  {
    id: "surprise_now",
    text: "10年前の自分が聞いたら驚くこと、今の自分にある？",
    placeholder: "例：まさか起業するとは思ってなかった",
    type: "auto_year",
    emoji: "🤯",
    timelineLabel: "10年前の私へ",
  },
  {
    id: "unexpected",
    text: "「これは自分でも意外だった」という選択は何かある？",
    placeholder: "例：文系なのにエンジニアになった",
    type: "text",
    emoji: "🎲",
    timelineLabel: "予想外の展開",
  },
  {
    id: "current_chapter",
    text: "今いる「章」に名前をつけるとしたら？",
    placeholder: "例：第5章 やっと自分らしくなってきた期",
    type: "text",
    emoji: "🌸",
    timelineLabel: "今の私の章",
  },
  {
    id: "next_chapter",
    text: "次の章のタイトルは何にしたい？",
    placeholder: "例：第6章 思いっきり羽ばたく期",
    type: "text",
    emoji: "🌈",
    timelineLabel: "未来の章",
  },
];
