import type { Question } from "./types";

// 14問の定義（章命名を廃止、タイトル＋詳細形式）
export const QUESTIONS: Question[] = [
  {
    id: "name_birth",
    text: "あなたのお名前と、生まれた年を教えてください",
    titlePlaceholder: "例：田中さくら",
    type: "text_with_year",
    emoji: "🍼",
    timelineLabel: "誕生",
    yearPlaceholder: "例：2000",
  },
  {
    id: "longest",
    text: "今も続けていることで、一番長く続いていることは？",
    titlePlaceholder: "例：日記を書くこと",
    textPlaceholder: "いつ頃から、どんな気持ちで続けてる？",
    type: "text_with_year",
    emoji: "🔥",
    timelineLabel: "ずっと続けていること",
    yearPlaceholder: "始めた年",
  },
  {
    id: "turning_point",
    text: "「あの選択をしたから今の私がある」という分岐点は？",
    titlePlaceholder: "例：地元を離れて上京した",
    textPlaceholder: "その選択をした理由や、その後どう変わった？",
    type: "text_with_year",
    emoji: "🚀",
    timelineLabel: "運命の分岐点",
    yearPlaceholder: "その年",
  },
  {
    id: "dark_period",
    text: "人生で一番どん底だった時期はいつ？",
    titlePlaceholder: "例：就活で全落ちした",
    textPlaceholder: "そのとき何を感じていた？",
    type: "text_with_year",
    emoji: "🌧️",
    timelineLabel: "試練の章",
    yearPlaceholder: "その年頃",
  },
  {
    id: "recovery",
    text: "そのどん底から、どうやって抜け出した？",
    titlePlaceholder: "例：友人に話を聞いてもらった",
    textPlaceholder: "どんなきっかけで立ち直れた？",
    type: "text",
    emoji: "☀️",
    timelineLabel: "再起の章",
  },
  {
    id: "golden",
    text: "「あの頃に戻りたいな」と思う時期はいつ？",
    titlePlaceholder: "例：高校の部活時代",
    textPlaceholder: "なぜその時期が好きだった？",
    type: "text_with_year",
    emoji: "🌟",
    timelineLabel: "黄金期",
    yearPlaceholder: "その年頃",
  },
  {
    id: "black_history",
    text: "反対に、「二度と戻りたくない」時期はある？",
    titlePlaceholder: "例：中二病全開の中学時代",
    textPlaceholder: "差し支えなければ、どんな時期だった？",
    type: "text_with_year",
    emoji: "🙈",
    timelineLabel: "黒歴史期",
    yearPlaceholder: "その年頃",
  },
  {
    id: "biggest_change",
    text: "自分が一番変わったと感じた出来事は？",
    titlePlaceholder: "例：海外一人旅",
    textPlaceholder: "何がどう変わった？",
    type: "text_with_year",
    emoji: "✨",
    timelineLabel: "転換点",
    yearPlaceholder: "その年",
  },
  {
    id: "let_go",
    text: "手放したことで、かえって良かったものは？",
    titlePlaceholder: "例：SNSをやめた",
    textPlaceholder: "手放してみてどうだった？",
    type: "text",
    emoji: "🕊️",
    timelineLabel: "手放したもの",
  },
  {
    id: "key_person",
    text: "今の自分に一番影響を与えた人との出会いは？",
    titlePlaceholder: "例：大学のゼミの先生",
    textPlaceholder: "その人からどんな影響を受けた？",
    type: "text_with_year",
    emoji: "💕",
    timelineLabel: "大切な出会い",
    yearPlaceholder: "出会った年",
  },
  {
    id: "surprise_now",
    text: "10年前の自分が聞いたら驚くこと、今の自分にある？",
    titlePlaceholder: "例：まさか起業するとは",
    textPlaceholder: "10年前の自分に一言伝えるとしたら？",
    type: "auto_year",
    emoji: "🤯",
    timelineLabel: "10年前の私へ",
  },
  {
    id: "unexpected",
    text: "「これは自分でも意外だった」という選択は？",
    titlePlaceholder: "例：文系なのにエンジニアになった",
    textPlaceholder: "なぜその選択をしたの？",
    type: "text",
    emoji: "🎲",
    timelineLabel: "予想外の展開",
  },
  {
    id: "current_chapter",
    text: "今いる「章」に名前をつけるとしたら？",
    titlePlaceholder: "例：やっと自分らしくなってきた期",
    textPlaceholder: "今の自分をひとことで表すと？",
    type: "text",
    emoji: "🌸",
    timelineLabel: "今の私",
  },
  {
    id: "next_chapter",
    text: "次の章のタイトルは何にしたい？",
    titlePlaceholder: "例：思いっきり羽ばたく期",
    textPlaceholder: "これからどんなことをしてみたい？",
    type: "text",
    emoji: "🌈",
    timelineLabel: "未来の私へ",
  },
];
